### ISSUE TITLE
Update Elasticsearch from 2.4 to 6.1

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#169]
Update implementation to support remote ES 6.1
Add a way to spawn the ES process by mesh

## Tasks
* [x] Verify that embedded ES also works on windows. - 0.25PT
* [x] Update documentation - 0.25PT
* [x] We need to move all ES code to a dedicated elasticsearch module
* [x] ~~We need to add a way to dynamically load the ES extension~~
* [x] The ES connection details must be added to the `mesh.yml` file
* [x] Prefix the ES indices
* [x] Update demo data handling - 0.25PT
* [x] Add operation timeout handling
* [x] Make SearchProvider#clear() and SearchProvider#refresh() work async
* [x] Search endpoints should fail gracefully if ES is not configured or ready - 0.25PT
* [x] Add search query timeout handling.
* [x] Add way to fork ES process from Mesh (backwards compatibility)
* [x] Make ES integration optional. Mesh should also work without a configured ES connection.
* [x] Add watchdog for embedded ES process.  - 0.25PT
* [x] Check what happens with custom mappings which are not ES6 compliant. Reindex would fail in that situation. - 0.25PT
* [x] Filter language via query and use native ES paging instead of manual paging
