### ISSUE TITLE
Roadmap - Draft

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#194]
Preliminary list of features/tasks that influence the Road Map

* [ ] Vert.x 3.5.0 Update
* [ ] RXJava 2 Update
* [ ] Elasticsearch 5.6 Update
* [ ] Tinkerpop 3 support
* [ ] Schema Migration edge case handling (Bugfixes)
* [ ] Clustering tests execution fixes
* [ ] More consistency checks
* [ ] Mesh UI New
* [ ] Import / Export
* [ ] Plugin Management
* [ ] Sorting / Filtering
* [ ] HTTP/2 support / tests
* [ ] Monitoring via JMX
* [ ] OAuth support
