### ISSUE TITLE
Enhance Image API add Focal Point cropping

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#250]
# Focal Point cropping
Add focus point handling

* https://docs.imgix.com/apis/url/focalpoint-crop
* https://designshack.net/articles/mobile/focal-point-intelligent-cropping-of-responsive-images/
* Example: https://sandbox.imgix.com/view?hasAgreedToUploadTerms=1&url=https%3A%2F%2Fsandbox-uploads.imgix.net%2Fu%2F1515498973-de60397cb97e3b92759b6c883124c6ac%3Ffp-x%3D0.25%26fp-debug%3Dtrue%26fp-y%3D0.5%26w%3D200%26crop%3Dfocalpoint%26fit%3Dcrop%26h%3D150
* https://docs.imgix.com/tutorials/focal-point-cropping

## Tasks

* [ ] Reset focal point if the image is being resized. Resizing the image could invalidate the focal point
* [x] Validate the focal point against the image dimensions
* [x] Add focal point to rest model
* [x] Add focal point to graph model
* [x] Add focal point update handling
* [x] Add image dimensions graph model
* [x] Add image dimensions rest model
* [x] Add image dimensions update handling
* [x] Add changelog to determine image sizes?
* [x] Refactor parameter names
* [x] Make resizing crop mode aware
* [x] Document focal point cropping
* [x] Add focal point tests
* [x] Add focal point cropping to image service
* [x] Add focal point cropping to image REST API
* [x] Update mesh demos (update image parameters)
* [x] Update mesh documentation (renamed parameters)
* [x] Check whether fpz should work without w,h
* [x] Check why http://localhost:8080/api/v1/demo/webroot/images/ford-gt.jpg?fpx=0.5&fpy=0.35&fpz=3.0&w=800&h=200&crop=fp&fpdebug=true is not centered
* [x] Update mesh UI (update image parameters)
* [x] Check error for URL http://localhost:8080/api/v1/demo/webroot/images/ford-gt.jpg?fpx=0.5&fpy=0.5&fpz=2&w=500&h=1250&fpdebug=true&crop=fp

Refactor crop parameters
* ?cropx=1022&cropy=100&cropw=2&croph=400 -> ?rect=1022,100,2,400&crop=rect

Rename width param
* ?width=300 -> ?w=300

Override the pre-configured focalpoint or set a new one
* ?w=200&h=300&fpx=20&fpy=200&crop=fp

Cropping with pre-configured focalpoint
* ?w=200&h=300&crop=fp
