### ISSUE TITLE
Handle binary fileupload slug conflicts automatically

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#265]
The filename of binary fields should automatically be updated when a conflict with an existing slug has been detected. The uniqueness of the slug should be guaranteed.

# Tasks
* [ ] Add code to make slug for binary fields unique
* [ ] Make the rename operation optional
* [ ] Define and document the rename pattern
