### ISSUE TITLE
Queries fail if many indices are used

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#303]
Queries fail since the selected indices are part of the search query url:

```
[Forgiving Charmander] ERROR [OkHttp http://localhost:9200/...] - Info: Request failed - status: 400 body {{"error":{"root_cause":[{"type":"too_long_frame_exception","reason":"An HTTP line is larger than 4096 bytes."}],"type":"too_long_frame_exception","reason":"An HTTP line is larger than 4096 bytes."},"status":400}}
```

## TODOs:

* [x] Fix refresh calls
* [x] Fix delete index calls
* [x] Replace `_search` with `_msearch` in graphql search
* [x] Replace `_search` with `_msearch` in regular search
* [x] Replace `_search` with `_msearch` in raw search

**Comment by Jotschi** [comment]
Workaround:
Use `http.max_initial_line_length=64K` within `elasticsearch/config/elasticsearch.yml` to workaround the issue (works in most cases)
