### ISSUE TITLE
Keycloak Support

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#406]
## Tasks

* [x] Document protocolMapper options
* [x] Add OAuth handler to RouterStorage
* [x] Add configuration for OAuth Handler
* [x] Make auth handler implementation modular - It should be possible to hook in also different implementations at a later point
* [x] Add keycloak auth tests
* [x] Check how user-group relations can be stored in the realm.json file

## Questions:

* How should we handle updates to authenticated users? How can we keep the keycloak info with Gentics Mesh in-sync? -> Sync is invoked if the token id changes
* Which field do we use to id a user -> prefered_username
* Is it possible that the application updates user specific properties in keycloak? -> Not needed
* Can we map existing users to keycloak users? How? -> Not needed
* Should mapped roles automatically be created in Mesh? -> Is now possible
* Keycloak supports userroles how should we handle those roles? Should we just ignore them since Gentics Mesh currently does not support user roles? -> We deal with those if we implement user roles
* Keycloak supports hierarchical group structures. Does this have implications on the way we need to assign groups/roles in Mesh? -> Done via mapper script

**Comment by Jotschi** [comment]
Related PR: #405

**Comment by Jotschi** [comment]
Feature was released in 0.20.0
