### ISSUE TITLE
ES Ingest Attachment Processor Plugin support

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#407]
It should be possible to also automatically process uploaded document files and store the data in Elasticsearch.

## Tasks:

* [x] Add way to run ES tests with enabled ES ingest plugin
* [ ] ~Add configuration to specify a dedicated ingest node~
* [x] Add [ES Java Client](https://github.com/gentics/elasticsearch-java-client) methods to create and delete `_ingest/pipeline` configurations.
* [x] Figure out how to actually use the ingest pipeline in combination with batch requests
* [x] Add removal of pipelines to clear() method
* [x] Add pipeline check to index sync operation
* [x] Add ingest/pipeline handling in Mesh. Pipelines must be deleted when an index gets deleted.
* [x] Add base 64 data of documents (doc, pdf) to index requests - skip others.
* [x] Add static prefix to pipeline config name in preparation for https://github.com/gentics/mesh/issues/283
* [x] Rename the content field (e.g. source.content, data.content, file.content)
* [x] Update file mapping to include the binary file metadata
* [x] Add custom mapping support for binary field schemas
* [x] Add tests
* [x] Add documentation 
* [x] Add changelog
* [x] Check whether an automatic changelog entry to reindex data is needed
* [x] Add way to detect whether the ES plugin is loaded or not. We need to be able to apply a fallback mechanism.

**Comment by Jotschi** [comment]
Released with 0.21.0
