### ISSUE TITLE
Index PDF Metadata

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#437]
It would be useful to also parse for PDF metadata and add this data to the search document.

### PDF Box

```java
PDDocument doc = PDDocument.load(new File("test.pdf"));
PDDocumentInformation info = doc.getDocumentInformation();
for (String key : info.getMetadataKeys()) {
	String value = info.getCustomMetadataValue(key);
	System.out.println("Key: {" + key + "} = {" + value + "}");
}
```

```xml
<dependency>
	<groupId>org.apache.pdfbox</groupId>
	<artifactId>pdfbox</artifactId>
	<version>2.0.9</version>
</dependency>
```

### Tika

```java
BodyContentHandler handler = new BodyContentHandler(-1);
Metadata metadata = new Metadata();
FileInputStream inputstream = new FileInputStream(new File("test.pdf"));
ParseContext pcontext = new ParseContext();

PDFParser pdfparser = new PDFParser();
pdfparser.parse(inputstream, handler, metadata, pcontext);

System.out.println("Metadata of the PDF:");
String[] metadataNames = metadata.names();

for (String name : metadataNames) {
	System.out.println("{" + name + "}={" + metadata.get(name) + "}");
}
```

### Tika (Generic)

```java
File file = new File("test.jpg");

Parser parser = new AutoDetectParser();
BodyContentHandler handler = new BodyContentHandler(-1);
Metadata metadata = new Metadata();
FileInputStream inputstream = new FileInputStream(file);
ParseContext context = new ParseContext();

parser.parse(inputstream, handler, metadata, context);
System.out.println("File content : " + handler.toString());

System.out.println("Metadata of the PDF:");
String[] metadataNames = metadata.names();

for (String name : metadataNames) {
	System.out.println("{" + name + "}={" + metadata.get(name) + "}");
}
```

## Tasks

* [x] Add meta data extraction
* [x] Update document mapping
* [x] Use geopoint datatype for lon/lat information
* [x] Add tests
* [x] Add documentation
* [x] Add changelog
* [x] Evaluate whether it would be possible to provide a way to hook into binary data streams in order to prepare for image meta data extraction
* [ ] Evaluate whether this could be a custom extension / plugin

**Comment by Jotschi** [comment]
Add generic impl. to BinaryFieldHandler#332

**Comment by Jotschi** [comment]
Released in 0.22.0
