### ISSUE TITLE
Refactor Event Handling

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#649]
The event handling must be reworked to provide events which can be consumed by the ES index handler. (#522)

## Tasks: 
* [x] Add event models
* [x] Add event batch handling (Events should be triggered when a bulk action is being processed)
* [x] Check that the branchUuid is always present in node events.
* [x] Should node migration events contain specific information? The indexer needs to be able to remove the document from index A and insert it into index B.

**Comment by Jotschi** [comment]
# Actions

| Action                        | Objects              | Events                     | Cause          | Endpoint                                          |
| ----------------------------- |:--------------------:|:--------------------------:|:--------------:|:--------------------------------------------------|
| Update user                   | user                 | `mesh.user.updated`        | -              | `POST /users/:uuid`                               |
| Delete user                   | user                 | `mesh.user.deleted`        | -              | `DELETE /users/:uuid`                             |
| Create user                   | user                 | `mesh.user.created`        | -              | `POST /users`                                     |
| Update role                   | role                 | `mesh.role.updated`        | -              | `POST /roles/:uuid`                               |
| Delete role                   | role                 | `mesh.role.deleted`        | -              | `DELETE /roles/:uuid`                             |
| Create role                   | role                 | `mesh.role.created`        | -              | `POST /roles`                                     |
| Set permissions               | role, element        | TBD                        | -              | `POST /roles/:roleUuid/permissions/:path`         |
| Update group                  | group                | `mesh.group.updated`       | -              | `POST /groups/:uuid`                              |
| Delete group                  | group                | `mesh.group.deleted`       | -              | `DELETE /groups/:uuid`                            |
| Create group                  | group                | `mesh.group.created`       | -              | `POST /groups`                                    |
| Update project                | project              | `mesh.project.updated`     | -              | `POST /projects/:uuid`                            |
| Delete project                | project              | `mesh.project.deleted`     | -              | `DELETE /projects/:uuid`                          |
| Create project                | project              | `mesh.project.created`     | -              | `POST /projects`                                  |
| Update schema                 | schema               | `mesh.schema.updated`      | -              | `POST /schemas/:uuid`                             |
| Delete schema                 | schema               | `mesh.schema.deleted`      | -              | `DELETE /schemas/:uuid`                           |
| Create schema                 | schema               | `mesh.schema.created`      | -              | `POST /schemas`                                   |
| Update microschema            | microschema          | `mesh.microschema.updated` | -              | `POST /microschemas/:uuid`                        |
| Delete microschema            | microschema          | `mesh.microschema.deleted` | -              | `DELETE /microschemas/:uuid`                      |
| Create microschema            | microschema          | `mesh.microschema.created` | -              | `POST /microschemas`                              |
| Assign user to group          | group, user          | TBD                        | -              | `POST /groups/:groupUuid/users/:userUuid`         |
| Uassign user from group       | group, user          | TBD                        | -              | `DELETE /groups/:groupUuid/users/:userUuid`       |
| Assign role to group          | group, role          | TBD                        | -              | `POST /groups/:groupUuid/roles/:roleUuid`         |
| Unassign role from group      | group, role          | TBD                        | -              | `DELETE /groups/:groupUuid/roles/:roleUuid`       |
| Apply changes to schema       | schema               | TBD                        | -              | `POST /schemas/:schemaUuid/changes`               |
| Apply changes to microschema  | microschema          | TBD                        | -              | `POST /microschemas/:microschemaUuid/changes`     |
| Repair graph                  | -                    | TBD                        | -              | `POST /admin/consistency/repair`                  |
| Backup graph                  | -                    | TBD                        | -              | `POST /admin/consistency/backup`                  |
| Restore graph                 | -                    | TBD                        | -              | `POST /admin/consistency/restore`                 |
| Reset job                     | job                  | TBD                        | -              | `DELETE /admin/jobs/:jobUuid`                     |
| Deploy plugin                 | plugin               | TBD(deploying, deployed)   | -              | `POST /admin/plugins`                             |
| Undeploy plugin               | plugin               | TBD                        | -              | `DELETE /admin/plugins`                           |
| Process jobs                  | elements             | TBD                        | -              | `POST /admin/processJobs`                         |
| Clear index                   | -                    | TBD                        | -              | `POST /search/clear`                              |
| Sync index                    | -                    | TBD                        | -              | `POST /search/sync`                               |
| Update node                   | node, tags?, tagfamilies?  | TBD                  | -              | `POST /:project/nodes/:uuid`                      |
| Delete node                   | node                 | TBD                        | -              | `DELETE /:project/nodes/:uuid`                    |
| Create node                   | node                 | TBD                        | -              | `POST /:project/nodes`                            |
| Delete node language          | node                 | TBD                        | -              | `DELETE /:project/nodes/:uuid/languages/:lang`    |
| Publish node language         | node                 | TBD                        | -              | `POST /:project/nodes/:uuid/languages/:lang/published` |
| Move node                     | node                 | TBD                        | -              | `POST /:project/nodes/:uuid/moveTo/:uuid`          |
| Publish all languages         | node                 | TBD                        | -              | `POST /:project/nodes/:uuid/published`             |
| Unpublish all languages       | node                 | TBD                        | -              | `POST /:project/nodes/:uuid/published`             |
| Upload binary                 | node                 | `mesh.node.updated`        | -              | `POST /:project/nodes/:uuid/binary/:name`          |
| Create branch                 | branch, nodes?       | TBD                        | -              | `POST /:project/branches`                          |
| Update branch                 | branch,nodes?        | TBD                        | -              | `POST /:project/branches/:uuid`                    |
| Assign tag to node            | node, tag?           | TBD                        | -              | `POST /:project/nodes/:uuid/tags`                  |
| Unassign tag to node          | node, tag?           | TBD                        | -              | `DELETE /:project/nodes/:uuid/tags/:tag`           |
| Transform binary of node      | node                 | TBD                        | -              | `POST /:project/nodes/:uuid/binaryTransform/:name` |
| Update tagfamily              | tagfamily            | `mesh.tagfamily.updated`   | -              | `POST /:project/tagFamilies/:uuid`                 |
| Delete tagfamily              | tagfamily            | `mesh.tagfamily.deleted`   | -              | `DELETE /:project/tagFamilies/:uuid`               |
| Create tagfamily              | tagfamily            | `mesh.tagfamily.created`   | -              | `POST /:project/tagFamilies`                       |
| Update node via webroot       | node                 | `mesh.node.updated`        | -              | `POST /:project/webroot/:path`                     |
| Create node via webroot       | node                 | `mesh.node.created`        | -              | `POST /:project/webroot/:path`                     |
| Create tag                    | tag                  | TBD                        | -              | `POST /:project/tagFamilies/:uuid/tags` |
| Update tag                    | tag                  | TBD                        | -              | `POST /:project/tagFamilies/:uuid/tags/:uuid` |
| Delete tag                    | tag                  | TBD                        | -              | `DELETE /:project/tagFamilies/:uuid/tags/:uuid` |
| Set latest branch             | branch               | TBD                        | -              | `POST /:project/branches/:uuid/latest` |
| Assign microschema to branch  | branch, schema?, node? | TBD                      | -              | `POST /:project/branches/:uuid/microschemas` |
| Assign schema to branch       | branch, schema?, node? | TBD                      | -              | `POST /:project/branches/:uuid/schemas` |
| Tag branch                    | branch,tag?          | TBD                        | -              | `POST /:project/branches/:uuid/tags` |
| Migrate schemas               | nodes?               | TBD                        | -              | `POST /:project/branches/:uuid/migrateSchemas` |
| Migrate microschemas          | nodes?               | TBD                        | -              | `POST /:project/branches/:uuid/migrateMicroschemas` |
| Assign schema to project      | project?             | TBD                        | -              | `POST /:project/schemas` |
| Unassign schema from project  | project?             | TBD                        | -              | `DELETE /:project/schemas/:uuid` |
| Assign microschema to project | project?             | TBD                        | -              | `POST /:project/microschemas` |
| Unassign microschema from project | project?         | TBD                        | -              | `DELETE /:project/microschemas/:uuid` |
