### ISSUE TITLE
Add Hugo support

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#726]
We should add support for the Hugo Static Site generator

# Idea

Create an exporter tool which generates markdown files from the Gentics Mesh nodes which contain the fields as `front-matter` parameters.

```
---
fields.name: "name field value"
fields.price: 2
fields.labels: ["a", "b", "c"]
---
```

A Hugo theme can use these parameters to generate the site.

## Initial work
https://github.com/gentics/mesh-hugo-exporter

```
usage: mesh-hugo-exporter
 -c,--clean           Clean output directory
 -help                print this message
 -k,--key <arg>       API Key
 -o,--output <arg>    Output directory (default: content)
 -p,--project <arg>   Project name to export
 -url <arg>           Gentics Mesh API URL (e.g.
                      https://demo.getmesh.io/api/v1/)
```
## TODO

* [x] Handle command line arguments
* [x] Handle basic fields
* [x] Export binary data
* [x] Export nodes as markdown files
* [ ] Handle micronode fields
* [x] Add example theme
* [x] Handle conflicting param keys (e.g. slug, name)
* [x] Handle `_index.md` vs. `index.md`
