### ISSUE TITLE
Smart Crop and Resize

### ISSUE THREAD

**Issue by Jotschi** [gentics/mesh#849]
Resizing images will currently cause images to be skewed when the given `h` and `w` aspect ratio does not match up with the aspect ratio of the crop area.

Example: 
* https://demo.getmesh.io/api/v1/demo/webroot/images/gulfstream-g550.jpg?crop=rect&h=20&w=200&rect=404,274,198,100

We should add another option or mode which will affect the resize operation that will be executed after the image has been cropped.

## `resize=force`

Forces the aspect ratio to the given values. This may result in skewed images

## `resize=smart` / `crop=rect-smart`

The cropped image will automatically be cropped again. Areas either _left, right_ or _top, bottom_ will be removed to match the crop area with the aspect ratio of the target image size which has been specified by the `w` and `h` parameter.

**Comment by Jotschi** [comment]
# TODO

* [ ] Add tests
* [ ] Add documentation for new parameters
* [ ] Add `resize` parameter to `ImageManipulationParameters/ImageManipulationParametersImpl` ( `force`, `smart`) 
* [ ] Implement smart resizing according to: `https://git.gentics.com/psc/node/blob/release/node-lib/src/main/java/com/gentics/lib/image/SmarterResizeFilter.java` in `ImgscalrImageManipulator#134`
* [ ] Check whether we want to change the default. If not: we might need to update the portal/cms logic
